# Generated by Django 5.2.4 on 2025-07-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('isin', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('cusip', models.CharField(blank=True, max_length=9, null=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Stock'), ('BOND', 'Bond'), ('ETF', 'Exchange Traded Fund'), ('MUTUAL_FUND', 'Mutual Fund'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Cryptocurrency'), ('REIT', 'Real Estate Investment Trust'), ('INDEX', 'Index')], max_length=20)),
                ('security_type', models.CharField(blank=True, max_length=30, null=True)),
                ('primary_exchange', models.CharField(max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('country', models.CharField(max_length=2)),
                ('sector', models.CharField(blank=True, choices=[('ENERGY', 'Energy'), ('MATERIALS', 'Materials'), ('INDUSTRIALS', 'Industrials'), ('CONSUMER_DISCRETIONARY', 'Consumer Discretionary'), ('CONSUMER_STAPLES', 'Consumer Staples'), ('HEALTHCARE', 'Healthcare'), ('FINANCIALS', 'Financials'), ('INFORMATION_TECHNOLOGY', 'Information Technology'), ('COMMUNICATION_SERVICES', 'Communication Services'), ('UTILITIES', 'Utilities'), ('REAL_ESTATE', 'Real Estate')], max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('coupon_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('credit_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('fund_family', models.CharField(blank=True, max_length=100, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('average_volume', models.BigIntegerField(blank=True, null=True)),
                ('is_actively_traded', models.BooleanField(default=True)),
                ('data_source', models.CharField(default='yfinance', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'security',
                'indexes': [models.Index(fields=['sector', 'asset_class'], name='security_sector_1df373_idx'), models.Index(fields=['currency', 'country'], name='security_currenc_bf28fe_idx'), models.Index(fields=['price_updated_at'], name='security_price_u_b7cc60_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('adjusted_close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('dividend_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('split_ratio', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='securities.security')),
            ],
            options={
                'indexes': [models.Index(fields=['security', 'date'], name='securities__securit_9e1c6a_idx'), models.Index(fields=['date'], name='securities__date_f4d920_idx')],
                'unique_together': {('security', 'date')},
            },
        ),
    ]
