# Generated by Django 5.2.4 on 2025-08-11 20:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('regime_type', models.CharField(choices=[('BULL', 'Bull Market'), ('BEAR', 'Bear Market'), ('SIDEWAYS', 'Sideways/Range-bound'), ('HIGH_VOLATILITY', 'High Volatility'), ('LOW_VOLATILITY', 'Low Volatility')], max_length=20)),
                ('vix_level', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('market_trend', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('volatility_regime', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('bid_size', models.BigIntegerField(blank=True, null=True)),
                ('ask_size', models.BigIntegerField(blank=True, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('avg_volume_10d', models.BigIntegerField(blank=True, null=True)),
                ('avg_volume_30d', models.BigIntegerField(blank=True, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('market_timestamp', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('lookback_period', models.IntegerField()),
                ('volatility_annualized', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('var_95', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('var_99', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('alpha', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('correlation_market', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('total_return', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('annualized_return', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('lookback_period', models.IntegerField()),
                ('price_correlation', models.DecimalField(decimal_places=4, max_digits=6)),
                ('return_correlation', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('return_covariance', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sma_20', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('sma_200', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ema_12', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ema_26', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('macd_line', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('support_level', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('resistance_level', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('REDUCE', 'Reduce Position'), ('INCREASE', 'Increase Position')], max_length=20)),
                ('signal_source', models.CharField(choices=[('MOMENTUM', 'Momentum Strategy'), ('MEAN_REVERSION', 'Mean Reversion'), ('TECHNICAL', 'Technical Analysis'), ('FUNDAMENTAL', 'Fundamental Analysis'), ('RISK_MANAGEMENT', 'Risk Management'), ('PORTFOLIO_REBALANCE', 'Portfolio Rebalancing')], max_length=30)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=4)),
                ('target_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('time_horizon', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='security',
            name='security_sector_1df373_idx',
        ),
        migrations.RemoveIndex(
            model_name='security',
            name='security_price_u_b7cc60_idx',
        ),
        migrations.RenameIndex(
            model_name='security',
            new_name='securities__currenc_92da40_idx',
            old_name='security_currenc_bf28fe_idx',
        ),
        migrations.RemoveField(
            model_name='security',
            name='sub_industry',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='return_1d',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='adjusted_close',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='close_price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='dividend_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='high_price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='low_price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='open_price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='securities.security'),
        ),
        migrations.AlterField(
            model_name='security',
            name='asset_class',
            field=models.CharField(choices=[('EQUITY', 'Stock'), ('ETF', 'ETF'), ('BOND', 'Bond'), ('MUTUAL_FUND', 'Mutual Fund'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Cryptocurrency'), ('REIT', 'REIT'), ('INDEX', 'Index'), ('OPTION', 'Option'), ('FUTURE', 'Future')], max_length=20),
        ),
        migrations.AlterField(
            model_name='security',
            name='coupon_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['asset_class', 'sector'], name='securities__asset_c_8f39a5_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['is_actively_traded'], name='securities__is_acti_7a5794_idx'),
        ),
        migrations.AlterModelTable(
            name='security',
            table=None,
        ),
        migrations.AddField(
            model_name='marketsnapshot',
            name='security',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_market_data', to='securities.security'),
        ),
        migrations.AddField(
            model_name='riskmetrics',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='securities.security'),
        ),
        migrations.AddField(
            model_name='securitycorrelation',
            name='security_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_first', to='securities.security'),
        ),
        migrations.AddField(
            model_name='securitycorrelation',
            name='security_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_second', to='securities.security'),
        ),
        migrations.AddField(
            model_name='technicalindicators',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='securities.security'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_signals', to='securities.security'),
        ),
        migrations.AddIndex(
            model_name='riskmetrics',
            index=models.Index(fields=['security', 'calculation_date'], name='securities__securit_2a255d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmetrics',
            index=models.Index(fields=['sharpe_ratio'], name='securities__sharpe__f9cdd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskmetrics',
            unique_together={('security', 'calculation_date', 'lookback_period')},
        ),
        migrations.AddIndex(
            model_name='securitycorrelation',
            index=models.Index(fields=['security_1', 'security_2'], name='securities__securit_5570a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securitycorrelation',
            unique_together={('security_1', 'security_2', 'calculation_date', 'lookback_period')},
        ),
        migrations.AddIndex(
            model_name='technicalindicators',
            index=models.Index(fields=['security', 'date'], name='securities__securit_9cf0cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalindicators',
            unique_together={('security', 'date')},
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['security', 'is_active'], name='securities__securit_7ab43b_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['signal_type', 'is_active'], name='securities__signal__eef508_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['created_at'], name='securities__created_e3592e_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['strength'], name='securities__strengt_7664e2_idx'),
        ),
    ]
