# Generated by Django 5.2.4 on 2025-08-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_marketregime_marketsnapshot_riskmetrics_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='security',
            new_name='security_asset_c_d016e5_idx',
            old_name='securities__asset_c_8f39a5_idx',
        ),
        migrations.RenameIndex(
            model_name='security',
            new_name='security_currenc_bf28fe_idx',
            old_name='securities__currenc_92da40_idx',
        ),
        migrations.RenameIndex(
            model_name='security',
            new_name='security_is_acti_a2c8ed_idx',
            old_name='securities__is_acti_7a5794_idx',
        ),
        migrations.AlterModelTable(
            name='security',
            table='security',
        ),
    ]
