# Generated by Django 5.2.4 on 2025-08-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_rename_securities__asset_c_8f39a5_idx_security_asset_c_d016e5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='sub_industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
