# Generated by Django 5.2.4 on 2025-09-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_security_sub_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='name',
        ),
        migrations.RemoveField(
            model_name='security',
            name='price_updated_at',
        ),
    ]
