# Generated by Django 5.2.4 on 2025-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_remove_security_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
