# Generated by Django 5.2.4 on 2025-07-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_profile',
        ),
    ]
