# Generated by Django 5.2.4 on 2025-09-15 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('min_weight_constraint', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('max_weight_constraint', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('state', models.CharField(default='active', max_length=10)),
                ('is_core_holding', models.BooleanField(default=False)),
                ('is_restricted', models.BooleanField(default=False)),
                ('last_rebalance_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.security')),
            ],
            options={
                'db_table': 'holdings',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=10)),
                ('remaining_quantity', models.DecimalField(decimal_places=6, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='accounts.holding')),
            ],
            options={
                'db_table': 'lots',
                'ordering': ['purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('cash_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('last_rebalance_date', models.DateTimeField(blank=True, null=True)),
                ('drift_threshold', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.portfolio'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Cash Deposit'), ('withdrawal', 'Cash Withdrawal'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('interest', 'Interest')], max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.holding')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.portfolio')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('portfolio', 'security')},
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('securities_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_return', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.portfolio')),
            ],
            options={
                'db_table': 'portfolio_snapshots',
                'ordering': ['-date'],
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
