# Generated by Django 5.2.4 on 2025-07-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_account_name_alter_holdings_name'),
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='current_price',
        ),
        migrations.AlterField(
            model_name='holdings',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.security'),
        ),
    ]
