# Generated by Django 5.2.4 on 2025-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_holdings_current_price_alter_holdings_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
