# Generated by Django 5.2.4 on 2025-08-10 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_cash_balance_account_drift_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=10)),
                ('remaining_quantity', models.DecimalField(decimal_places=6, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.holdings')),
            ],
            options={
                'db_table': 'lots',
            },
        ),
    ]
