# Generated by Django 5.2.4 on 2025-09-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_lots'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='portfolio',
        ),
    ]
