# Generated by Django 5.2.4 on 2025-09-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='drift_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
