# Generated by Django 5.2.4 on 2025-09-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_drift_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='account',
        ),
    ]
