# Generated by Django 5.2.4 on 2025-09-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_transactions_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.holdings'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Cash Deposit'), ('withdrawal', 'Cash Withdrawal'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('interest', 'Interest')], max_length=10),
        ),
    ]
