# Generated by Django 5.2.4 on 2025-09-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_transactions_account_transactions_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
